services:
  mysql-db1:
    image: mysql:latest
    container_name: mysql-db1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Floppy_Bird_DB1
    ports:
      - "3308:3306"
    volumes:
      - ./dbvol/db1_data:/var/lib/mysql
      - ./mysql/init/db1:/docker-entrypoint-initdb.d
    networks:
      - mysql_network

  mysql-db2:
    image: mysql:latest
    container_name: mysql-db2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Floppy_Bird_DB2
    ports:
      - "3309:3306"
    volumes:
      - ./dbvol/db2_data:/var/lib/mysql
      - ./mysql/init/db2:/docker-entrypoint-initdb.d
    networks:
      - mysql_network


  node_api:
    build: bitnami/express:latest
    container_name: node_api
    expose:
      - "3000"
    environment:
      - DB_HOST=mysql-db2
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=Floppy_Bird_DB2
    volumes:
    - ./WebComponents/NodeJs/app:/usr/src
    depends_on:
      - mysql-db1
      - mysql-db2

  nginx:
    image: nginx:latest
    container_name: nginx_webserver
    ports:
      - "80:80"
    volumes:
      - ./WebComponents/nginx/config/default.conf:/etc/nginx/conf.d/default.conf  # Mount custom Nginx configuration
      - ./WebComponents/HTML&CSS:/usr/share/nginx/html                 # Serve static game files
      - ./WebComponents/Game:/usr/share/nginx/html
    depends_on:
      - node_api

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - mysql_network

volumes:
  db1_data:
  db2_data:

networks:
  mysql_network:
