version: '3.8'
services:
  mysql-db1:
    image: mysql:latest
    container_name: mysql-db1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Floppy_Bird_DB1
    ports:
      - "3308:3306"
    volumes:
      - db1_data:/var/lib/mysql
      - ./mysql/init/db1:/docker-entrypoint-initdb.d
    networks:
      - mysql_network

  mysql-db2:
    image: mysql:latest
    container_name: mysql-db2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Floppy_Bird_DB2
    ports:
      - "3309:3306"
    volumes:
      - db2_data:/var/lib/mysql
      - ./mysql/init/db2:/docker-entrypoint-initdb.d
    networks:
      - mysql_network

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - mysql_network

volumes:
  db1_data:
  db2_data:

networks:
  mysql_network:
