version: '3.8'

services:
  
  mysql-floppy_birddb1:
    image: mysql:latest
    container_name: mysql-floppy_birddb1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: floppy_birddb1
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/dbimport/Floppy_Bird_DB.sql:/docker-entrypoint-initdb.d/Floppy_Bird_DB.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
    networks:
      - backend

  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"  # Maps port 80 in the container to port 8080 on your host
    volumes:
      - ./nginx/html:/usr/share/nginx/html          # Mounts HTML files and stylesheets
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf  # Mounts custom Nginx config
    networks:
      - backend

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      mysql-floppy_birddb1:
        condition: service_healthy
    ports:
      - "8081:8080"  # Changed to avoid conflict with nginx
    networks:
      - backend
      
networks:
  backend:
    driver: bridge
